backend:
  name: github
  repo: birminghamstudentsforlife/birminghamstudentsforlife.github.io
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow


media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "page"
    label: "Page"
    folder: "/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "post"
    label: "Post"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Date"
        name: "date"
        widget: "hidden"
        default: true
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        allow_multiple: false
      - label: "Header Image"
        name: "header-image"
        widget: "image"
        allow_multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"